### ISSUE TITLE
[IDEA] An option to force the website to dark/light mode

### ISSUE THREAD

**Issue by Aaron-Mok** [zetxek/adritian-free-hugo-theme#113]

**Comment by zetxek** [comment]
Thanks for the suggestion @Aaron-Mok :) 

I had actually looked into the way that Papermod does it - and I liked it:


![image](https://github.com/user-attachments/assets/9443414c-ef39-483a-bbde-61efc0e1c116)

Currently the theme uses the system settings, but i think it's valuable to turn it off and on.

I'll check this - should be doable, as bootstrap supports the change from media queries to data attributes.
