### ISSUE TITLE
toml stream error on themes.toml

### ISSUE THREAD

**Issue by evolutionise** [zetxek/adritian-free-hugo-theme#14]
Hi - first off, thank you for providing this free theme! 

I'm trying to set it up to run on my Windows 11 Pro desktop and I'm running into this warning once I try to run the server:

`> hugo.exe server -D`
`WARN  Failed to read module config for "adritian-free-hugo-theme" in "C:\\Hugo\\Sites\\alix\\themes\\adritian-free-hugo-theme\\theme.toml": "_stream.toml:2:9": unmarshal failed: toml: expected character =`

I think this is because [theme.toml](https://github.com/zetxek/adritian-free-hugo-theme/blob/main/theme.toml) is actually a YAML format - verified by running the contents of the file through a YAML linter 😆 

![image](https://github.com/zetxek/adritian-free-hugo-theme/assets/6320469/dc000ab0-46d0-45c5-b533-675f7c1d79e8)

I don't think this error is critical as it continues to run, although I then hit a different problem, for which I will open a separate issue.

**Comment by zetxek** [comment]
Thanks for spotting, reporting and fixing it :)
In my dev environment in OS X as well as with the linux-based demo sites I had not spotted the error. 
But makes complete sense - it was definitely a `yml` file 😅
