### ISSUE TITLE
spelling mistake in themes/adritian-free-hugo-theme/exampleSite/hugo.toml line 68

### ISSUE THREAD

**Issue by techwriter-pooja** [zetxek/adritian-free-hugo-theme#41]
Hello,

Thanks for the beautiful template. However, there is a small issue in the themes/adritian-free-hugo-theme/exampleSite/hugo.toml line 68. 

Original: draft = false
Need to change to: draft = false

**Comment by zetxek** [comment]
Hej @techwriter-pooja, thanks for reporting! 
I think that the part that you mention is not the correct one though (the `draft = false` one).

https://github.com/zetxek/adritian-free-hugo-theme/blob/main/exampleSite/hugo.toml#L68
```
      enabled = fale
```

Should be 

```
      enabled = false
```
