### ISSUE TITLE
The items under experience section are not displaying

### ISSUE THREAD

**Issue by marctalcott** [zetxek/adritian-free-hugo-theme#49]
Great template. I love it. 
<img width="1072" alt="image" src="https://github.com/user-attachments/assets/298e574a-6aef-4674-87e8-189f7986c244">
The left side should contain 3 jobs if you are using code from the example site folder. I assume you are because I get the same result when running locally. The 3 items under the job history don't display. Is this an easy fix?

**Comment by zetxek** [comment]
Oh, I realize why this was under the radar.
In https://adritian-demo.vercel.app/ (https://github.com/zetxek/adritian-demo) I'm not rendering the "Experience" section 🙈

**Comment by zetxek** [comment]
Fixed by #50 :)
Thanks for reporting it!

**Comment by marctalcott** [comment]
Thanks. That was easy :)
