### ISSUE TITLE
Broken URL on README.md

### ISSUE THREAD

**Issue by nurfaizfoat** [zetxek/adritian-free-hugo-theme#58]
On the first paragraph, the URL was not pasted properly - resulted to broken link

`See it live at **[adritian-demo.vercel.app](https://https://adritian-demo.vercel.app/)** ` 
need to be changed to
`See it live at **[adritian-demo.vercel.app](https://adritian-demo.vercel.app/)** `

**Comment by zetxek** [comment]
Thank you for spotting and even more for reporting!! 

This should be a quick fix later :)
