### ISSUE TITLE
Readme Error

### ISSUE THREAD

**Issue by martinsam** [zetxek/adritian-free-hugo-theme#66]
Replace : 

Replace the config.toml file in the project's root directory with themes/adritian-free-hugo-theme/exampleSite/config.toml: cp themes/adritian-free-hugo-the

By 
Replace the hugo.toml file in the project's root directory with themes/adritian-free-hugo-theme/exampleSite/config.toml: cp themes/adritian-free-hugo-the

**Comment by zetxek** [comment]
Thank you @martinsam!
Fix incoming...
