### ISSUE TITLE
some (basic) i18n features

### ISSUE THREAD

**Issue by martinsam** [zetxek/adritian-free-hugo-theme#67]
What does "Basic" mean?
For i18n, the language files should be in the i18n folder and a minimum of settings in hugo.toml. Do you think it would be interesting if I spent some time making the texts "read more, about me, form contact ..  internationalizable"?

**Comment by zetxek** [comment]
> What does "Basic" mean? For i18n, the language files should be in the i18n folder and a minimum of settings in hugo.toml. Do you think it would be interesting if I spent some time making the texts "read more, about me, form contact .. internationalizable"?

It would definitely be appreciated! Basic is that there I had started when Hugo didn't have i18n - so it was done "manually"...

Let me look into what we need to add - but you are very welcome to do so!

**Comment by martinsam** [comment]
Here is a quick example of the mechanism


https://github.com/zetxek/adritian-free-hugo-theme/compare/main...martinsam:adritian-free-hugo-theme:main

**Comment by zetxek** [comment]
> Here is a quick example of the mechanism
> 
> [main...martinsam:adritian-free-hugo-theme:main](https://github.com/zetxek/adritian-free-hugo-theme/compare/main...martinsam:adritian-free-hugo-theme:main)

gotcha, I can make this happen!

**Comment by zetxek** [comment]
I've been a happy trigger and merged to main 😆 
But I'm working on the i18n features for the site in  https://github.com/zetxek/adritian-free-hugo-theme/tree/add/i18n-support :)

**Comment by zetxek** [comment]
A first step for this is in https://github.com/zetxek/adritian-free-hugo-theme/pull/78 now. 
It misses fallback options and a link to existing languages at the moment - but you can check it already @martinsam

**Comment by zetxek** [comment]
Fixed in https://github.com/zetxek/adritian-free-hugo-theme/pull/78.
Mind that the change is breaking, due to the way in which multilingual content is handled - not in the config files, but in dedicated translation files for each language.

**Comment by martinsam** [comment]
Great job, I'll take a moment during the week to check. Thanks
