### ISSUE TITLE
Support for more social icons

### ISSUE THREAD

**Issue by dougalb** [zetxek/adritian-free-hugo-theme#83]
Is there a way to add more social icons e.g. BlueSky and Threads?

**Comment by zetxek** [comment]
It seems that @lukasbableck fork  (https://fontello.bableck.dev/) could do the trick :) 

It has fontawesome 6 - that has icons for x, threads or bluesky.

<img width="980" alt="image" src="https://github.com/user-attachments/assets/99ee4f61-931a-4139-a577-69cc16eed229">

<img width="969" alt="image" src="https://github.com/user-attachments/assets/d454a75f-4972-40b4-8f54-0cc0d2a70983">

<img width="1068" alt="image" src="https://github.com/user-attachments/assets/f8d47b76-07b4-45e4-bab5-18ebf3b76bb4">

This might be the next theme upgrade - can't promise a time, but can be done

**Comment by zetxek** [comment]
In the end I could fit this @dougalb - you can preview them at https://adritian-demo-git-theme-update-update-theme-697534-adrianmoreno.vercel.app/.

There are some small changes with the naming - but shouldn't be anything too dramatic to update (I hope, otherwise let me know).

**Comment by dougalb** [comment]
That's awesome! Thank you!
