### ISSUE TITLE
The quote icon is not show in Testimonials section

### ISSUE THREAD

**Issue by dcorto** [zetxek/adritian-free-hugo-theme#88]
The problem is in the file `layouts/partials/testimonial.html`

```
<div class="col-12 col-md-4 mb-5 mb-md-0 testimonial">
                <i class="icon-quote"></i>
                <p>
                    {{ .Content }}
                </p>
```

The class should be **"icon-quote-left"** instead of "icon-quote" (icon-quote do not exists on the icons css file)

I can create a quick PR and fix if @zetxek 

Let me know if the solution make sense for you @zetxek 

Thanks ;)

**Comment by zetxek** [comment]
It makes all sense! If you open a PR i can approve it right away :)
